defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - continue-on-error: true
      name: Build
      run: ./gradlew build
    - continue-on-error: true
      if: always()
      name: Upload build data
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: 'btrace-dist/build

          '
        retention-days: 1
    - continue-on-error: true
      if: always()
      name: Archive test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: '**/reports/**/*

          '
  cleanup:
    needs: publish
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cleanup temporary artifacts
      uses: geekyeggo/delete-artifact@v5
      with:
        name: build
  publish:
    if: github.ref ==  'refs/heads/develop' || github.ref == 'refs/heads/master'
    needs: test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Download build data
      uses: actions/download-artifact@v4
      with:
        name: build
    - continue-on-error: true
      env:
        BTRACE_SONATYPE_PWD: ${{ secrets.BTRACE_SONATYPE_PWD }}
        BTRACE_SONATYPE_USER: ${{ secrets.BTRACE_SONATYPE_USER }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGNING_PWD: ${{ secrets.GPG_SIGNING_PWD }}
      name: Deploy Maven
      run: ./gradlew -x test :btrace-dist:publish
  test:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - continue-on-error: true
      name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Download build data
      uses: actions/download-artifact@v4
      with:
        name: build
        path: btrace-dist/build
    - continue-on-error: true
      name: Run tests
      run: './gradlew -Pintegration :integration-tests:test

        '
    - continue-on-error: true
      if: always()
      name: Integration test reports
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-reports-${{ matrix.java }}
        path: 'integration-tests/build/reports/**/*

          '
    - continue-on-error: true
      if: success() && matrix.java == '11'
      name: Archive binary artifacts
      uses: actions/upload-artifact@v4
      with:
        name: btrace-dist
        path: 'btrace-dist/build/distributions/**/btrace-*-bin*.tar.gz

          '
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
    timeout-minutes: 10
name: BTrace CI/CD
on:
  repository_dispatch:
    types: trigger-ga___continuous.yml
